language: php

sudo: false

php:
  - 7.0
  - 7.1

before_script:
    - composer install --no-interaction
    - php bin/console doctrine:database:create --env=test
    - php bin/console doctrine:schema:update --force --env=test

script: ./vendor/bin/simple-phpunit
